import esbuild from "esbuild";
import fs from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";
import process from "process";
import { buildWorker, HOST_PACKAGES } from "./scripts/worker-bundle.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

// Inline any imported `.wasm` file into the bundle as a base64 string.
//
// Not the `binary` loader: that emits this same base64 literal wrapped in esbuild's `__toBinary`
// helper and bound to a top-level `var`, so the whole 1.9 MB module is decoded synchronously at
// plugin load rather than when (or if) the interpreter is first used. See `src/wasm.d.ts`.
const wasmPlugin = {
  name: "wasm",
  setup(build) {
    build.onResolve({ filter: /\.wasm$/ }, (args) => {
      if (args.resolveDir === "") {
        return undefined;
      }
      return {
        path: path.isAbsolute(args.path) ? args.path : path.join(args.resolveDir, args.path),
        namespace: "numbat-wasm-binary",
      };
    });
    build.onLoad({ filter: /.*/, namespace: "numbat-wasm-binary" }, async (args) => ({
      contents: await fs.promises.readFile(args.path),
      loader: "base64",
    }));
  },
};

/** Inject the built worker as `import workerSource from "symbat:worker-source"`. */
const workerSourcePlugin = {
  name: "worker-source",
  setup(build) {
    build.onResolve({ filter: /^symbat:worker-source$/ }, (args) => ({
      path: args.path,
      namespace: "symbat-worker-source",
    }));
    build.onLoad({ filter: /.*/, namespace: "symbat-worker-source" }, async () => {
      const { source, inputs } = await buildWorker(prod);
      workerBytes = Buffer.byteLength(source);
      return {
        contents: `export default ${JSON.stringify(source)};`,
        loader: "js",
        watchFiles: inputs,
      };
    });
  },
};

// Set by the plugin above on every (re)build, so the budget check below reports the size that was
// actually produced rather than re-deriving it.
let workerBytes = 0;

// -- Budgets --------------------------------------------------------------------------------------

// Two, because a single `main.js < 3.1 MB` is 88% a budget on the wasm module: it moves whenever
// NUMBAT_TAG moves and says nothing at all about the code. These are sized so that each fails for
// one reason, and names it.

/** The worker's own code. Tight enough that pulling a whole subsystem across the seam fails here
 *  rather than in review. */
const WORKER_BUDGET = 64 * 1024;

/** `main.js` with the inlined module subtracted, which is the part anyone can affect. */
const PLUGIN_BUDGET = 512 * 1024;

function checkBudgets() {
  const wasmBytes = fs.statSync("src/wasm/pkg/numbat_wasm_bg.wasm").size;
  const inlined = Math.ceil(wasmBytes / 3) * 4;
  const bundleBytes = fs.statSync("main.js").size;
  const pluginBytes = bundleBytes - inlined;

  const failures = [];
  if (workerBytes > WORKER_BUDGET) {
    failures.push(
      `the interpreter worker is ${kib(workerBytes)}, over its ${kib(WORKER_BUDGET)} budget.\n`
        + "  Most likely something above the seam was pulled into src/interpreter/worker/**.",
    );
  }
  if (pluginBytes > PLUGIN_BUDGET) {
    failures.push(
      `main.js is ${kib(pluginBytes)} once the inlined wasm module is subtracted, over its `
        + `${kib(PLUGIN_BUDGET)} budget.\n`
        + "  Most likely a new dependency, or the worker bundle being injected twice.",
    );
  }

  if (failures.length > 0) {
    for (const failure of failures) {
      console.error(`Bundle budget: ${failure}`);
    }
    process.exit(1);
  }

  console.log(`worker ${kib(workerBytes)}, plugin ${kib(pluginBytes)} (+ ${kib(inlined)} inlined wasm)`);
}

function kib(bytes) {
  return `${(bytes / 1024).toFixed(1)} KiB`;
}

// -- The main pass --------------------------------------------------------------------------------

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [...HOST_PACKAGES, ...builtinModules],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [wasmPlugin, workerSourcePlugin],
});

if (prod) {
  await context.rebuild();
  checkBudgets();
  process.exit(0);
} else {
  await context.watch();
}
